package com.ronin.kernel.shm

import com.ronin.kernel.IInferenceService
import com.ronin.kernel.NativeEngine
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject

/**
 * Requirement 6 & 7: Cloud & Local AI Review Pipeline
 * Routes analysis requests to cloud Gemini/OpenRouter or local Gemma 4 E2B models.
 * Enforces privacy controls (no raw sensor data sent without user approval).
 */
object ShmAiReviewPipeline {

    suspend fun analyzeSession(
        session: ShmSession,
        options: ExportOptions,
        useLocalModel: Boolean,
        nativeEngine: NativeEngine?,
        inferenceService: IInferenceService?,
        provider: String = "Gemini",
        modelId: String = "gemini-2.5-flash",
        apiKey: String = ""
    ): AIReviewResult = withContext(Dispatchers.IO) {
        try {
            // Requirement Phase 2.2: AI Payload Optimization (Use truncated/extracted payload)
            val optimizedPayload = session.toOptimizedAiPayload(options)

            val prompt = """
                You are an SHM engineering assistant.
                Analyze this structural vibration session.
                Explain:
                1. Current health condition
                2. Resonance frequency meaning
                3. Possible anomalies
                4. Recommended follow-up measurement
                
                [SHM Structural Session Data]
                $optimizedPayload
            """.trimIndent()

            val timeoutMillis = if (useLocalModel) 45_000L else 30_000L
            val rawResponseText = kotlinx.coroutines.withTimeout(timeoutMillis) {
                if (useLocalModel) {
                    // Requirement 7: Local Gemma Model routing
                    if (inferenceService == null && nativeEngine?.inferenceService == null) {
                        throw ShmError.AIReviewError("Local AI Review failed: Local InferenceService is not bound or running.")
                    }
                    val payload = JSONObject().apply {
                        put("prompt", prompt)
                        put("max_tokens", 512)
                        put("temperature", 0.2)
                    }
                    val activeService = inferenceService ?: nativeEngine?.inferenceService
                    val resStr = activeService?.runReasoning(payload.toString()) ?: ""
                    if (resStr.isBlank()) {
                        throw ShmError.AIReviewError("Local AI Review failed: Empty response from local Gemma engine.")
                    }
                    val resObj = try { JSONObject(resStr) } catch (_: Exception) { JSONObject() }
                    if (!resObj.optBoolean("success", true)) {
                        val errMsg = resObj.optString("error", "Unknown local engine error")
                        throw ShmError.AIReviewError("Local AI Review failed: $errMsg")
                    }
                    resObj.optString("text", resObj.optString("response", resStr))
                } else {
                    // Requirement 6: Cloud Gemini / OpenRouter / OpenAI Review
                    if (nativeEngine == null) {
                        throw ShmError.AIReviewError("Cloud AI review failed: Native engine bridge disconnected.")
                    }
                    if (apiKey.isBlank() && !provider.equals("Custom", ignoreCase = true)) {
                        throw ShmError.AIReviewError("Cloud AI review failed: API key is missing for provider '$provider'. Please configure your key in Settings.")
                    }

                    val resultStr = nativeEngine.performCloudInferenceAsync(prompt, provider, apiKey)
                    val resObj = try { JSONObject(resultStr) } catch (_: Exception) { JSONObject() }
                    
                    if (resObj.has("error") || !resObj.optBoolean("success", true)) {
                        val err = resObj.opt("error")
                        val errDetail = when (err) {
                            is JSONObject -> err.optString("message", err.toString())
                            is String -> err
                            else -> "Network timeout or invalid API response"
                        }
                        throw ShmError.AIReviewError("Cloud AI review failed: $errDetail")
                    }
                    
                    resObj.optString("text", resObj.optString("response", "No explanation generated by cloud model."))
                }
            }

            if (rawResponseText.isBlank()) {
                throw ShmError.AIReviewError("AI review returned an empty explanation. Please check your model connection or token limits.")
            }

            AIReviewResult.fromAIResponse(rawResponseText)
        } catch (e: kotlinx.coroutines.TimeoutCancellationException) {
            val limitSec = if (useLocalModel) "45" else "30"
            throw ShmError.AIReviewError("Inference timed out after ${limitSec}s. Please check network connectivity or local model load.", e)
        } catch (e: ShmError.AIReviewError) {
            throw e
        } catch (e: Exception) {
            val errorMsg = if (e.message?.contains("timeout", ignoreCase = true) == true) {
                "Cloud AI review failed: Network timeout during model inference."
            } else {
                "Cloud AI review failed: ${e.message ?: "Unknown inference exception"}"
            }
            throw ShmError.AIReviewError(errorMsg, e)
        }
    }
}
