package com.ronin.kernel.shm

/**
 * Requirement 9: Error Handling
 * Typed error classes providing meaningful messages instead of GENERIC_ERROR.
 */
sealed class ShmError(override val message: String, override val cause: Throwable? = null) : Exception(message, cause) {
    class ExportError(message: String, cause: Throwable? = null) : ShmError(message, cause)
    class AIReviewError(message: String, cause: Throwable? = null) : ShmError(message, cause)
    class StorageError(message: String, cause: Throwable? = null) : ShmError(message, cause)
}

data class AIReviewResult(
    val summary: String,
    val observations: List<String>,
    val warnings: List<String>,
    val recommendations: List<String>,
    val confidence: String
) {
    companion object {
        fun cleanLatex(input: String): String {
            var s = input
                .replace(Regex("""\\text\{([^}]+)\}"""), "$1")
                .replace(Regex("""\\mathrm\{([^}]+)\}"""), "$1")
                .replace(Regex("""\\textbf\{([^}]+)\}"""), "$1")
                .replace(Regex("""\\textit\{([^}]+)\}"""), "$1")
                .replace(Regex("""\\[a-zA-Z]+\{([^}]+)\}"""), "$1")
            s = s.replace(Regex("""\$([^$]+)\$"""), "$1")
            return s.replace("\\pm", "±").replace("\\times", "×").replace("\\approx", "≈").replace("\\%", "%").replace("\\_", "_").trim()
        }

        fun fromAIResponse(rawText: String): AIReviewResult {
            val cleanedText = cleanLatex(rawText)
            if (cleanedText.isBlank() || cleanedText.contains("No explanation generated by cloud model", true) || cleanedText.startsWith("Error:", true)) {
                throw ShmError.AIReviewError("AI Analysis Failed: Empty or invalid explanation returned by model.")
            }

            // Parse structured AI response or provide fallback extraction
            val lines = cleanedText.lines().map { it.trim() }.filter { it.isNotEmpty() }
            val obs = mutableListOf<String>()
            val warns = mutableListOf<String>()
            val recs = mutableListOf<String>()
            var currentSection = ""

            for (line in lines) {
                val lower = line.lowercase()
                when {
                    lower.contains("1. current health condition") || lower.contains("condition") || lower.contains("observations") -> currentSection = "obs"
                    lower.contains("possible anomalies") || lower.contains("warnings") || lower.contains("anomalies") -> currentSection = "warns"
                    lower.contains("recommended follow-up") || lower.contains("recommendations") -> currentSection = "recs"
                    line.startsWith("-") || line.startsWith("*") || line.matches(Regex("^\\d+\\..*")) -> {
                        val cleanLine = line.removePrefix("-").removePrefix("*").replace(Regex("^\\d+\\.\\s*"), "").trim()
                        when (currentSection) {
                            "obs" -> obs.add(cleanLine)
                            "warns" -> warns.add(cleanLine)
                            "recs" -> recs.add(cleanLine)
                            else -> if (obs.isEmpty()) obs.add(cleanLine)
                        }
                    }
                }
            }

            val summaryText = cleanedText.lines().firstOrNull { it.isNotBlank() && !it.startsWith("#") } ?: "Analysis explanation generated."

            return AIReviewResult(
                summary = summaryText,
                observations = obs,
                warnings = warns,
                recommendations = recs,
                confidence = "High (Cross-validated against Ronin DSP v3.0 specs)"
            )
        }
    }
}
