// android/build.gradle
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.21"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.3.21"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
